name: Push to main

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Push to main branch
      uses: ad-m/github-push-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REMOTE: origin
        BRANCH: main
